### ISSUE TITLE
Collision error

### ISSUE THREAD

**Issue by clarkeash** [laravel-zero/installer#1]
I have done a fresh install of the installer:

```bash
composer global require laravel-zero/installer
```

when I run `laravel-zero` I get the following error:

```
Uncaught Error: Class 'NunoMaduro\Collision\Provider' not found in /Users/clarkeash/.composer/vendor/laravel-zero/framework/src/Providers/ErrorHandler/ErrorHandler.php:29
```

You have collision in require-dev, should it not be in require instead?

**Comment by nunomaduro** [comment]
@clarkeash Your problem was solved via hot-fix.

Please perform:

`composer clear && composer global remove laravel-zero/installer && composer global require laravel-zero/installer`
