### ISSUE TITLE
Installer on Windows don't rename the application

### ISSUE THREAD

**Issue by epiecs** [laravel-zero/installer#6]
Hi,

Whenever I try and install a new laravel zero cli app i get the following error:

```
In Process.php line 1160:

The process "composer create-project laravel-zero/laravel-zero testapp --prefer-dist" exceeded the timeout of 60 seconds
```

I am running php 7.2.5. composer is fully updated.

This is the output of my terminal:

```
C:\Users\35gbers\Desktop\Projects>laravel-zero new testapp
Crafting application..

Installing laravel-zero/laravel-zero (v5.6.16)
  - Installing laravel-zero/laravel-zero (v5.6.16): Loading from cache
Created project in punchCli
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 62 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.9): Loading from cache
  - Installing symfony/process (v4.0.9): Loading from cache
  - Installing jolicode/jolinotif (v2.0.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing symfony/finder (v4.0.9): Loading from cache
  - Installing symfony/console (v4.0.9): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/translation (v4.0.9): Loading from cache
  - Installing nesbot/carbon (1.27.0): Loading from cache
  - Installing league/flysystem (1.0.44): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing illuminate/contracts (v5.6.20): Loading from cache
  - Installing illuminate/support (v5.6.20): Loading from cache
  - Installing illuminate/console (v5.6.20): Loading from cache
  - Installing nunomaduro/laravel-desktop-notifier (v2.0.3): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.1): Loading from cache
  - Installing nunomaduro/laravel-console-task (v1.0.4): Loading from cache
  - Installing nunomaduro/laravel-console-summary (v1.0.1): Loading from cache
  - Installing beberlei/assert (v2.9.5): Loading from cache
  - Installing php-school/cli-menu (2.1.0): Loading from cache
  - Installing nunomaduro/laravel-console-menu (v1.0.2): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing filp/whoops (2.1.14): Loading from cache
  - Installing nunomaduro/collision (v2.0.2): Loading from cache
  - Installing laravel-zero/foundation (v5.6.17): Loading from cache
  - Installing illuminate/filesystem (v5.6.20): Loading from cache
  - Installing illuminate/container (v5.6.20): Loading from cache
  - Installing illuminate/events (v5.6.20): Loading from cache
  - Installing illuminate/config (v5.6.20): Loading from cache
  - Installing illuminate/cache (v5.6.20): Loading from cache
  - Installing laravel-zero/framework (v5.6.16): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (3.0.0): Loading from cache
  - Installing sebastian/comparator (3.0.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (6.1.1): Loading from cache
  - Installing phpunit/php-timer (2.0.0): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.0.0): Loading from cache
  - Installing phpunit/php-code-coverage (6.0.4): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.6): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (7.1.5): Loading from cache

In Process.php line 1160:

  The process "composer create-project laravel-zero/laravel-zero testapp --prefer-dist" exceeded the timeout of 60 s
  econds.
```

**Comment by nunomaduro** [comment]
Hey @epiecs . Please try this: 

1. `composer config --global process-timeout 2000`. 
2. `composer create-project laravel-zero/laravel-zero testapp --prefer-dist`.

**Comment by epiecs** [comment]
Hi,

I already upped my process-timeout to 2000. I found online that the timeout of composer is 300 seconds btw and not 60 seconds.

Now I get this error:

```
--OUTPUT OMITTED--
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.6.0)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files
> @php application app:rename
Renaming the application...

 What is your application name?:
 >

  Aborted
```

I don't cancel the installation nor do  I press ctrl+c etc... Even when I don't touch anything the installer will abort by itself.

P.S. What I forgot to mention yesterday is that when I did this:

```
composer global remove laravel-zero/installer
composer create-project --prefer-dist laravel-zero/laravel-zero testapp
```

That I would get the same "aborted" error as described above. So I think that there are 2 problems at the moment. One where the globally installed laravel-zero installer times out when I use it and on the other hand that when the install is done using the non global installer method that it gives the "aborted" error.

Thanks for the quick replies btw!

**Comment by nunomaduro** [comment]
@epiecs Are you using the Windows 10’s New Bash Shell ?

**Comment by epiecs** [comment]
I get the error when I use the normal windows cmd prompt. If I use the linux subsystem with bash I don't get the error. 

The error also persists even when I run the shell in legacy mode.

**Comment by epiecs** [comment]
P.S. When I use bash for windows I am using this on a clean install on the latest version of windows 10. I also installed php 7.2 etc...

After the installation succeeds I try to follow your guide to rename the app but the output stays blank and returns to the terminal. Also running `php test-cli` does nothing.

**Comment by epiecs** [comment]
Hi,

I think I found something. The issues with the normal cmd prompt are most likely due to bugs with that prompt and composer.

However,

When I run this command in bash `laravel-zero new ticket-cli`

The installer completes the install. At the end I get the following output:

```
Writing lock file
Generating autoload files
Application ready! Build something amazing.
```

Normally I would be able to cd to the ticket-cli directory and be able to run the command `php ticket-cli` to get the basic help of the shell but it won't work.

![image](https://user-images.githubusercontent.com/124507/39747929-f93bfefe-52ae-11e8-9952-e2fa80be9dbb.png)

As you can see the laravel-zero installer hasn't renamed the file named application to ticket-cli. This also explains why the command app:rename wouldnt work. I needed to use application:rename.

Hope this helps.

**Comment by nunomaduro** [comment]
@epiecs You are now able to use `php application` right ?

**Comment by epiecs** [comment]
Yes, when i use php application everything works. I just use php application to manually rename application then to the real name.

1. `laravel-zero new test-cli`
2. `cd test-cli`
3. `php application app:rename test-cli`
4. `php test-cli` then works

All of this is in the linux shell btw. Not the windows cmd shell.

Maybe something goes wrong at the end of the installer where it forgets to rename the application        file to the correct name?

**Comment by nunomaduro** [comment]
@epiecs Maybe. I will take a look into to it. Or try reproduce that with someone that have a windows machine. Thanks!

**Comment by epiecs** [comment]
No problem, Love the framework!

**Comment by nunomaduro** [comment]
@epiecs Issue still exists?

**Comment by nunomaduro** [comment]
I will close this issue due the lack of activity.

**Comment by epiecs** [comment]
Sorry for the late response, I know how to work around the issue but the issue still persists. I recorded what happens with asciinema:

https://asciinema.org/a/ZkqPRjg11lwKBjlr4b81mkfgW
